#application: titalab-tita
#version: alpha-001
runtime: php72
service: php73
#api_version: 1
#threadsafe: yes

#env_variables:
  #TWILIO_ACCOUNT_SID : "AC3788a89abfdd94f54d06e986de83e2c9"
  #TWILIO_AUTH_TOKEN : "9d9f87d8b1474c3a3f27bb1b2bf1e24c"
  #TWILIO_WHATSAPP_NUMBER : "+14155238886"
  #MY_WHATSAPP_NUMBER : "+51933248701"

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

# Serve a directory as a static resource.
#- url: /stylesheets
#  static_dir: stylesheets

# Serve images as static resources.
#- url: /(.+\.(gif|png|jpg))$
#  static_files: \1
#  upload: .+\.(gif|png|jpg)$

- url: /web/(.*\.(css|eot|gz|html|ico|js|map|png|svg|ttf|woff|woff2))
  static_files: content/web/\1
  upload: content/web/(.*\.(css|eot|gz|html|ico|js|map|png|svg|ttf|woff|woff2))

- url: /web/.*
  static_files: content/web/index.html
  upload: content/web/index.html
  secure: always
  
# Serve your app through a front controller at index.php or public/index.php.  
- url: .*
  script: auto